# Basic provisioning example
---
- name: create instance
  hosts: localhost
 


  tasks:
   - name: create ec2 instance
     ec2:
       aws_access_key: {access_key}
       aws_secret_key: {secret_key}
       image: ami-07c1207a9d40bc3bd
       wait: yes
       instance_type: t2.micro
       group_id: sg-03a9f978f95f86397
       key_name: art--key-pair
       region: us-east-2
       count_tag:
         Name: apacheserver
       exact_count: 1
     register: ec2
